### ISSUE TITLE
Proposal: Add "sleep" after each test

### ISSUE THREAD

**Issue by kurtismullins** [cloud-bulldozer/ocm-api-load#15]
Currently, all of the tests run back-to-back. This makes it slightly more difficult to observe metrics between each test as there's no obvious starting and stopping point from the server-side at a global level.

I propose that we add a Sleep call after each test to make it more obvious where one test ends and another begins. This can be set at a global level and made to be configurable. A sane default might be 3 minutes.

By specifying that it sleeps after each test, hopefully the garbage collection (performed at the end of the test-suite) is also separated.

**Comment by chentex** [comment]
This has been already implemented.
