### ISSUE TITLE
Use a config file for `endpoint : rate` management 

### ISSUE THREAD

**Issue by nimrodshn** [cloud-bulldozer/ocm-api-load#3]
Currently the `endpint : rate` ratio is statically defined within the [code base](https://github.com/cloud-bulldozer/ocm-api-load/blob/main/pkg/helpers/rates.go). We would like to move those to a dynamically loaded config file.

Using [viper](https://github.com/spf13/viper) is one option.

cc: @chentex @kurtismullins

**Comment by kurtismullins** [comment]
It may be useful to allow the override of duration for individual tests as well. Specifically to address the limitation on the amount of "Create Cluster" operations that can occur.
