### ISSUE TITLE
Container Image building is broken

### ISSUE THREAD

**Issue by chentex** [cloud-bulldozer/ocm-api-load#51]
## Problem

Building image is failing with this error:
```
file /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release from install of containers-common-2:1-23.module_el8.7.0+1106+45480ee0.x86_64 conflicts with file from package redhat-release-8.5-0.8.el8.x86_64
```

## Findings
The image based on UBI and we need to a the `centos8-appstream` repository for `skopeo` package. When trying to install the package [here](https://github.com/cloud-bulldozer/ocm-api-load/blob/main/Dockerfile#L5), it needs to install as a dependency the package `containers-commons` this dependency provides the file `/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release` (See file list Ref:1)

That file is already provided and protected in the UBI so the process fails with this error

```
Package redhat-release-8.5-0.8.el8.x86_64 is already installed.
Error: 
 Problem: The operation would result in removing the following protected packages: redhat-release
 ```
This happens also when trying to override the `redhat-release` package with a `centos-stream-release` one.

## Temporary solution

Use the `fedora` (Ref:2) image with tag `37` to be able to build the image until more data or the solution for this has been resolved. Implemented in #52 

## Needed Solution

Keep using the UBI image.
[_Edit_] At the time of updating is [UBI9](https://catalog.redhat.com/software/containers/ubi9/ubi/615bcf606feffc5384e8452e?container-tabs=overview)

## References
1: https://centos.pkgs.org/8-stream/centos-appstream-x86_64/containers-common-1.4.0-5.module_el8.5.0+878+851f435b.x86_64.rpm.html
2: https://hub.docker.com/_/fedora

**Comment by shahsahil264** [comment]
I tried building the image with UBI9, but got the same error again. I guess we'll have to wait more.
