### ISSUE TITLE
Add github workflow to ensure PRs can compile

### ISSUE THREAD

**Issue by kurtismullins** [cloud-bulldozer/ocm-api-load#9]
We don't have an actual test suite (which is okay!) but we should use Github Workflows or some low-barrier CI to simply compile the code and ensure it works with each PR. Optionally, including linting (`go fmt`) would be awesome as well.

**Comment by kurtismullins** [comment]
@rsevilla87 mentioned this exists as an example: https://github.com/cloud-bulldozer/kube-burner/blob/master/.github/workflows/go.yml

I wouldn't suggest a complete copy+paste but may be a quick & easy guide to getting started for those uninitiated with Github Actions.

**Comment by nimrodshn** [comment]
Sounds good @kurtismullins ! thanks a lot.

**Comment by chentex** [comment]
We can close this since we already have it.
